Sprint1/step2
JuliyaPekhota/react-burger pull request #2
Opened 2021-12-11 14:50 UTC by JuliyaPekhota

2021-12-12 16:38 UTC, grishbar requested changes
Отличная работа, круто, что все написано на typescript и функциональных компонентах, везде у компонентов корректно описаны типы.
Есть некоторые моменты, которые надо исправить для принятия работы:

- [ ] Закрытие попала должно происходить только при клике на оверлей, при клике на сам попап он не должен закрываться
- [ ] Надо переименовать все неудачно названные переменные
- [ ] Нужно разделить Стейт на отдельные примитивные объекты
- [ ] Добавить обработку статуса ответа при запросе на бэкенд
- [ ] Избавиться от дублирования кода

Удачи в рефакторинге

2021-12-12 16:38 UTC, grishbar commented on src/components/App/App.tsx
> +const URL = 'https://norma.nomoreparties.space/api/ingredients';
`можно лучше`
имя переменной URL слишком абстрактное, не очень понятно, что в ней лежит, будет лучше, если назовешь ее как нибудь INGREDIENTS_URL

2021-12-12 16:38 UTC, grishbar commented on src/components/App/App.tsx
> +  });
`надо исправить`
переменные состояния принято разделять, так как, так читается намного проще, и куда проще становится обновлять стейт, также тут бы переименовать эти переменные, так как data это очень абстрактное название, такая переменная может содержать все что угодно, давай сделаем, что нибудь типа:
```
 const [ingredients, setIngredients] = useState([]);
 const [isIngredientsLodaded, setIsIngredientsLodaded ] = useState(false);
```

2021-12-12 16:38 UTC, grishbar commented on src/components/App/App.tsx
> +      .then(res => setResult({ success: true, data: res.data }))
`надо исправить`
При совершении запроса, он может успешно выполнится и вернуться не с 2xx статусом и соответственно он будет содержать не данные для ингредиентов, и не совсем очевидно, но такой запрос не попадет в блок catch, только если у тебя не случится какая то скриптовая ошибка тут, например  в json не полчится преобразовать, только тогда ты попадешь в catch. Соответственно тебе тут нужно если не [response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) выкидывать ошибку, тогда тебя перекинет в блок catch

2021-12-12 16:38 UTC, grishbar commented on src/components/AppHeader/AppHeader.tsx
> +import s from './AppHeader.module.css';
`можно лучше`
возможно если во всем проекте стили будут названы одной буквой s, то это будет ок, и даже будет хорошим решением, так как не нужно будет постоянно длинное название переменной, но мне кажется, что мы не сильно потеряем если нормально назовем эту переменную. styles например

2021-12-12 16:38 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.module.css
> +}
`можно лучше`
старайся избегать комбинаторов по возможности, очень тяжело в будущем поддерживать такой код, и он очень чреват неожиданными багами, лучше всегда сделать отдельный класс и задать стили под него

2021-12-12 16:38 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const unLockData = props.burgers.filter((card : any) => card.type !== 'bun');
`надо исправить`
тут тоже не очень хорошее название переменной, оно не отражает то, что в ней содержится, ты в этой переменной хранишь начинки, давай так и назовем ее fillings

2021-12-12 16:38 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +                {card.type !== 'bun' && (<DragIcon type="primary" />)}
`надо исправить`
уже мапишься по ингридентам без булок, эта проверка тут излишняя

2021-12-12 16:38 UTC, grishbar commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +    const currentCard = props.burgers.filter(card => card._id === idCard);
`надо исправить`
кажется эта переменная тоже должна храниться в состоянии компонента, и обновляться при открытии модалки

2021-12-12 16:38 UTC, grishbar commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +        const scrollBottom = scroll ? scroll + (231/2) : 0;
`надо исправить`
у тебя в коде не должно быть магических переменных, 231/2 нужно вынести в переменную, и дать осмысленное название, и лучше не полагаться, на какие то абстрактные размеры переменных, будет хорошо, если сделаешь, не ориентируясь на них

2021-12-12 16:38 UTC, grishbar commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +        const pointMain = (mainRef && mainRef.current) ? mainRef.current.offsetTop : 0;
`можно лучше`
const pointMain = mainRef?.current?.offsetTop || 0;

2021-12-12 16:38 UTC, grishbar commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +                            })}
`надо исправить`
тут у тебя дублирование кода 3 раза, создай объект, который хранит нужные тебе данные, и промапайся по нему

2021-12-12 16:38 UTC, grishbar commented on src/components/ModalOverlay/ModalOverlay.module.css
> +  }*/
`можно лучше`
комментарии которые не документируют дальнейший код (не говорят, что будет происходит в последующих строчках под ними) должны быть удалены

2021-12-12 16:38 UTC, grishbar commented on src/styles/globals.css
> +}
`надо исправить`
шрифты надо вынести в отдельный файл fonts.css

2021-12-13 14:40 UTC, grishbar requested changes
Отличная работа, большинство проблем исправлено, давай еще парочку исправим и будет ок:

Пулл реквест должен быть сделан из ветки sprint-2/step-2
Убрать создание функций в jsx

Также обрати внимание на комментарии "можно лучше", их исправление поможет сделать твой код напорядок лучше

2021-12-13 14:40 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.module.css
> +    width: 8px !important;
`можно лучше`
Так как мы тут не верстку учим, то ок, но !important в твоем проекте быть не должно, вот [здесь](https://stackoverflow.com/questions/8360190/is-it-bad-to-use-important-in-a-css-property) есть подробное обсуждение на эту тему

2021-12-13 14:40 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.module.css
> +}
`можно лучше`
это прям совсем тяжелый скомбинированный селектор получился его переопределить будет совсем проблематично, так, что будет хорошо, если избавишься от него, а еще лучше от всех комбинаторов в проекте

2021-12-13 14:40 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +        isLocked={true}
`можно лучше`
можно просто isLocked

2021-12-13 14:40 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +                <div key={card._id} className={`${s.fillings} mb-4 mr-4 ml-4`}>
`можно лучше`
сейчас ок, но в дальнейшем у тебя ингредиенты могут дублироваться и такой key не подойдет
Также ты маппишься по fillings логично, что каждый отдельный элемент в нем будет filling а не card

2021-12-13 14:40 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  ) : null;
`можно лучше`
компонент модалки храни в jsx и показывай в зависимости от условия, выносить в отдельную переменную, излишне нагружает чтение кода

2021-12-13 14:40 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +        {constructorElements()}
`можно лучше`
это тоже на мой взгляд зря вынесено в функцию можно просто здесь описать

2021-12-13 14:40 UTC, grishbar commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +        </Modal>
`можно лучше`
давай это тоже перенесем в return твоего компонента

2021-12-13 14:40 UTC, grishbar commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +                                    <div onClick={() => handleOpenModal(card._id)} key={`_${card._id}`} className={`${s.card} pr-4 pl-4`}>
`надо исправить`
[нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это плохо влияет на производительность, и не [рекомендуется разработчиками реакта](https://ru.reactjs.org/docs/faq-functions.html)

2021-12-13 17:03 UTC, JuliyaPekhota commented on src/components/BurgerConstructor/BurgerConstructor.module.css
> +    width: 8px !important;
Также против использования правил с !important, но react-custom-scrollbars сложно перестилизовать, только если вернуть inline стили, которые пришлось вынести в css после первой проверки.

2021-12-13 17:45 UTC, JuliyaPekhota commented
почему sprint2 в названии ветки? задание по первому спринту

2021-12-13 17:47 UTC, grishbar commented
> почему sprint2 в названии ветки? задание по первому спринту

ой прости действительно ветка должна быть sprint-1/step-2

2021-12-13 20:27 UTC, grishbar commented
отлично, работу принимаю, удачи в дальнейшем обучении

2021-12-14 15:03 UTC, merged