sprint2/step1 Migrating State to Context
JuliyaPekhota/react-burger pull request #3
Opened 2021-12-18 19:56 UTC by JuliyaPekhota

2021-12-19 17:34 UTC, grishbar requested changes
В целом все хорошо, поправь пожалуйста редьюсер, для подсчета суммы согласно моему комментарию, и приму работу

2021-12-19 17:34 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  }
`надо исправить`
Не совсем корректно, ты тут описала reducer, соответственно он так и должен быть назван, totalCostReducer
Так как он отвечает за то, чтобы возвращать текущую стоимсоть бургера, то и подсчет этой стоимости должен происходить внутри него, при каждом изменении ингредиентов в бургере ты должна отправлять соответствующий экшен для пересчета цены в этот редьюсер и в ппэйлоаде переедавать ингредиенты. Хочу, чтобы было сделано так не потому, что я принимаю только одно решение, а потому что такое решение будет наиболее логичным и верным для той задачи которую пытаешься решить, а сейчас получился не совсем редьюсер.

2021-12-19 17:34 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const bun = ingredients[0];
`надо исправить`
ты не знаешь, каким ингредиентом придет булка, да, сейчас это работает корректно, но в любой момент, ответ бэка может поменяться и первым может прийти не булка, и все сломается. Находи пожалуйста булку по типу среди ингредиентов

2021-12-19 17:34 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const idsOrder = ingredients.map(card => card._id);
`можно лучше`
ingredientIds

2021-12-19 17:34 UTC, grishbar commented on src/components/App/App.tsx
> +          </IngredientsContext.Provider>
`можно лучше`
в рамках текщего тз ок, но помни, что контекст, это некоторый глобальный объект, который зачастую хочется, чтобы был доступен в любом месте проекта, поэтому было бы лучше, если бы ты все компоненты обернулся контекст провайдером

2021-12-21 06:17 UTC, JuliyaPekhota commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  }
поправила

2021-12-21 09:07 UTC, grishbar approved these changes
Отлично, работу принимаю, прости, что так долго не проверял, обрати пожалуйста внимание на комментарии "можно лучше", они помогут значительно улучшить твою работу, удачи в дальнейшем обучении

2021-12-21 09:07 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const bun = action.payload.filter((card: any) => card.type === 'bun')[0];
`можно лучше`
можно просто find

2021-12-21 09:07 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const totalSum = fillings.reduce((sum: any, current: any) => sum + current.price, 0) + (bun.price*2);
`можно лучше`
если у тебя нет булки, в ингредиентах, то bun.price*2 вызовет ошибку и приложение упадет

2021-12-21 09:07 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +      throw new Error(`Wrong type of action: ${action.type}`);
`можно лучше`
кажется было бы логичней, если бы у тебя был всегда тут один action "updateSumm", который пересчитывал бы сумму

2021-12-21 09:07 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +};
`можно лучше`
тебе вначале надо делать post запрос, и только после того как он успешно выполнится показывать модалку, в идеале еще пока он выполняется показывать лоадер. Так как сейчас ты покажешь модалку пустую, потом когда выполнится запрос дернется интерфейс и модалка заполнится, что очень некрасиво, и также если запрос упадет, модалка так и останется пустой.

2021-12-24 08:31 UTC, merged